### ISSUE TITLE
Use command line arguments to search 

### ISSUE THREAD

**Issue by miguel-nascimento** [ropoko/cli-dictionary#3]
Instead of running 
```bash
cli-dictionary
vida pt
```
it's more easier to run only 

```bash
cli-dictionary pt vida
```

**Comment by ropoko** [comment]
this issue is already known and it's under development 😅

I will close the issue after this new approach

and thanks! this help me to confirm that I on the right way!

**Comment by ropoko** [comment]
The new version 2.3.1 correct this issue, Thanks for sharing your ideas! feel free to open an PR or creating an new issue :D
